"""Student feedback report exporter for batch grading results.

Generates individual HTML reports per student showing their
score, percentage, and per-check results with feedback text.

No Qt dependencies - pure Python module.
"""

from __future__ import annotations

import html
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from grading.batch_grader import BatchGradingResult
    from grading.grader import GradingResult

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Grading Report - {student_file}</title>
<style>
body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
h1 {{ color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }}
.summary {{ background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 15px 0; }}
.summary p {{ margin: 5px 0; }}
.score {{ font-size: 1.4em; font-weight: bold; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
th {{ background: #4CAF50; color: white; padding: 10px; text-align: left; }}
td {{ padding: 8px 10px; border-bottom: 1px solid #ddd; }}
tr:nth-child(even) {{ background: #f9f9f9; }}
.pass {{ color: #388E3C; font-weight: bold; }}
.fail {{ color: #D32F2F; font-weight: bold; }}
.feedback {{ color: #666; font-style: italic; }}
footer {{ margin-top: 30px; color: #999; font-size: 0.9em; border-top: 1px solid #ddd; padding-top: 10px; }}
</style>
</head>
<body>
<h1>Grading Report</h1>
<div class="summary">
<p><strong>Student File:</strong> {student_file}</p>
<p><strong>Rubric:</strong> {rubric_title}</p>
<p class="score">Score: {earned}/{total} ({percentage:.1f}%)</p>
</div>

<h2>Check Results</h2>
<table>
<thead>
<tr><th>Check</th><th>Points</th><th>Result</th><th>Feedback</th></tr>
</thead>
<tbody>
{check_rows}
</tbody>
</table>

<footer>
Generated by Spice-GUI Grading System
</footer>
</body>
</html>
"""

_CHECK_ROW_TEMPLATE = """\
<tr>
<td>{check_id}</td>
<td>{earned}/{possible}</td>
<td class="{result_class}">{result_text}</td>
<td class="feedback">{feedback}</td>
</tr>"""


def generate_student_report_html(result: GradingResult) -> str:
    """Generate an HTML feedback report for a single student.

    Args:
        result: The grading result for one student.

    Returns:
        Complete HTML document as a string.
    """
    check_rows = []
    for cr in result.check_results:
        row = _CHECK_ROW_TEMPLATE.format(
            check_id=html.escape(cr.check_id),
            earned=cr.points_earned,
            possible=cr.points_possible,
            result_class="pass" if cr.passed else "fail",
            result_text="Pass" if cr.passed else "Fail",
            feedback=html.escape(cr.feedback) if cr.feedback else "",
        )
        check_rows.append(row)

    return _HTML_TEMPLATE.format(
        student_file=html.escape(result.student_file),
        rubric_title=html.escape(result.rubric_title),
        earned=result.earned_points,
        total=result.total_points,
        percentage=result.percentage,
        check_rows="\n".join(check_rows),
    )


def export_student_reports(
    result: BatchGradingResult,
    output_dir: str,
) -> list[str]:
    """Export individual HTML feedback reports for all students.

    Creates one HTML file per student in the output directory, named
    after the student's submission file.

    Args:
        result: Batch grading result with per-student results.
        output_dir: Directory to write report files.

    Returns:
        List of created file paths.

    Raises:
        OSError: If the output directory cannot be created or files can't be written.
    """
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    created_files = []
    for gr in result.results:
        # Generate filename from student file (strip extension, add .html)
        base_name = Path(gr.student_file).stem
        report_name = f"{base_name}_report.html"
        report_path = out_path / report_name

        html_content = generate_student_report_html(gr)
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        created_files.append(str(report_path))

    return created_files
