name: Bug Report
description: Report something that isn't working correctly
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below so we can reproduce and fix it.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Open the application
        2. Place a resistor on the canvas
        3. Try to connect a wire to terminal 2
        4. Wire snaps to wrong position
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows 11
        - Windows 10
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS (other)
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Linux (other)
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      options:
        - "3.13"
        - "3.12"
        - "3.11"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or error output
      description: Paste screenshots or error tracebacks here (if applicable).

  - type: textarea
    id: circuit-file
    attributes:
      label: Circuit file
      description: If relevant, paste the contents of your .json circuit file or attach it.
      render: json

  - type: checkboxes
    id: checked-existing
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and this hasn't been reported yet
          required: true
