name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for SDM Spice? We'd love to hear it.

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem does this solve? Who benefits?
      placeholder: "As a student working on lab assignments, I need to..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application does this relate to?
      options:
        - Circuit editor (canvas, components, wires)
        - Simulation (analysis types, ngspice)
        - UI/UX (layout, themes, usability)
        - File I/O (save, load, export)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Screenshots, mockups, links to similar tools, etc.
