"""Tests for CircuiTikZ LaTeX parser."""

import pytest
from simulation.circuitikz_parser import CircuitikzParseError, import_circuitikz


class TestBasicParsing:
    def test_parse_single_resistor(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert len(model.components) == 1
        assert "R1" in model.components
        assert model.components["R1"].component_type == "Resistor"
        assert model.components["R1"].value == "1k"

    def test_parse_multiple_components(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 2) to[R, l=$R1$, a={1k}] (0, 1);
  \draw (0, 1) to[C, l=$C1$, a={10u}] (0, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert len(model.components) == 2
        assert "R1" in model.components
        assert "C1" in model.components
        assert model.components["C1"].component_type == "Capacitor"
        assert model.components["C1"].value == "10u"

    def test_parse_voltage_source(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[V, l=$V1$, a={5V}] (0, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert "V1" in model.components
        assert model.components["V1"].component_type == "Voltage Source"
        assert model.components["V1"].value == "5V"


class TestComponentTypes:
    def test_parse_inductor(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[L, l=$L1$, a={10m}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["L1"].component_type == "Inductor"

    def test_parse_diode(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[D, l=$D1$] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["D1"].component_type == "Diode"

    def test_parse_current_source(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[I, l=$I1$, a={1m}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["I1"].component_type == "Current Source"


class TestGroundParsing:
    def test_parse_ground(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
  \node[ground] at (0, 0) {};
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert any(c.component_type == "Ground" for c in model.components.values())


class TestTripoles:
    def test_parse_npn(self):
        tex = r"""
\begin{circuitikz}
  \node[npn] (Q1) at (2, 2) {};
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert "Q1" in model.components
        assert model.components["Q1"].component_type == "BJT NPN"

    def test_parse_opamp(self):
        tex = r"""
\begin{circuitikz}
  \node[op amp] (U1) at (3, 2) {};
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert "U1" in model.components
        assert model.components["U1"].component_type == "Op-Amp"


class TestWireParsing:
    def test_parse_wire(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 2) to[R, l=$R1$, a={1k}] (0, 1);
  \draw (0, 2) to[C, l=$C1$, a={10u}] (2, 2);
  \draw (0, 1) -- (2, 1);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        # Wire should be parsed (may or may not match terminals depending on positions)
        assert len(model.components) == 2


class TestStandaloneDocument:
    def test_parse_standalone(self):
        tex = r"""
% Generated by Spice-GUI
\documentclass[border=10pt]{standalone}
\usepackage[siunitx]{circuitikz}
\begin{document}
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
\end{circuitikz}
\end{document}
"""
        model, _ = import_circuitikz(tex)
        assert len(model.components) == 1
        assert "R1" in model.components


class TestValueExtraction:
    def test_extracts_value_from_annotation(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={4.7k\Omega}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert "4.7k" in model.components["R1"].value

    def test_default_value_when_missing(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        # Should get a default value for Resistor
        assert model.components["R1"].value != ""


class TestControlledSourceDisambiguation:
    """Issue #520: CircuiTikZ round-trip conflates CCVS with VCVS and CCCS with VCCS."""

    def test_ccvs_preserved_via_spice_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled voltage source, l=$H1$, a={1k}] (1.5, -0.5); % spice: CCVS
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["H1"].component_type == "CCVS"

    def test_cccs_preserved_via_spice_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled current source, l=$F1$, a={1}] (1.5, -0.5); % spice: CCCS
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["F1"].component_type == "CCCS"

    def test_vcvs_default_without_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled voltage source, l=$E1$, a={10}] (1.5, -0.5);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["E1"].component_type == "VCVS"

    def test_vccs_default_without_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled current source, l=$G1$, a={1m}] (1.5, -0.5);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["G1"].component_type == "VCCS"

    def test_full_round_trip_ccvs(self):
        """Export a CCVS and reimport — must come back as CCVS, not VCVS."""
        from models.circuit import CircuitModel
        from models.component import ComponentData
        from simulation.circuitikz_exporter import generate

        ccvs = ComponentData("H1", "CCVS", "1k", position=(100, 100))
        model = CircuitModel()
        model.add_component(ccvs)
        model.rebuild_nodes()

        tex = generate(model.components, model.wires, model.nodes, model.terminal_to_node)
        reimported, warnings = import_circuitikz(tex)

        assert len(warnings) == 0
        assert reimported.components["H1"].component_type == "CCVS"

    def test_full_round_trip_cccs(self):
        """Export a CCCS and reimport — must come back as CCCS, not VCCS."""
        from models.circuit import CircuitModel
        from models.component import ComponentData
        from simulation.circuitikz_exporter import generate

        cccs = ComponentData("F1", "CCCS", "1", position=(100, 100))
        model = CircuitModel()
        model.add_component(cccs)
        model.rebuild_nodes()

        tex = generate(model.components, model.wires, model.nodes, model.terminal_to_node)
        reimported, warnings = import_circuitikz(tex)

        assert len(warnings) == 0
        assert reimported.components["F1"].component_type == "CCCS"


class TestFourTerminalControlPair:
    """Issue #523: 4-terminal component control pair lost during reimport."""

    def test_vcvs_control_pair_imported(self):
        tex = r"""
\begin{circuitikz}
  \draw (4.5, 0.5) to[american controlled voltage source, l=$E1$, a={10}] (4.5, -0.5);
  \draw[dashed] (1.5, 0.5) to[short] (1.5, -0.5); % ctrl: E1
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert "E1" in model.components
        comp = model.components["E1"]
        assert comp.component_type == "VCVS"
        # 4-terminal component should have 4 terminal positions recorded
        terms = comp.get_terminal_positions()
        assert len(terms) == 4

    def test_vccs_control_pair_imported(self):
        tex = r"""
\begin{circuitikz}
  \draw (4.5, 0.5) to[american controlled current source, l=$G1$, a={1m}] (4.5, -0.5);
  \draw[dashed] (1.5, 0.5) to[short] (1.5, -0.5); % ctrl: G1
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        comp = model.components["G1"]
        assert comp.component_type == "VCCS"
        terms = comp.get_terminal_positions()
        assert len(terms) == 4

    def test_full_round_trip_four_terminal(self):
        """Export a VCVS and reimport — all 4 terminal positions should survive."""
        from models.circuit import CircuitModel
        from models.component import ComponentData
        from simulation.circuitikz_exporter import generate

        vcvs = ComponentData("E1", "VCVS", "10", position=(100, 100))
        model = CircuitModel()
        model.add_component(vcvs)
        model.rebuild_nodes()

        tex = generate(model.components, model.wires, model.nodes, model.terminal_to_node)
        reimported, warnings = import_circuitikz(tex)

        assert len(warnings) == 0
        comp = reimported.components["E1"]
        assert comp.component_type == "VCVS"
        terms = comp.get_terminal_positions()
        assert len(terms) == 4

    def test_vc_switch_control_pair_imported(self):
        tex = r"""
\begin{circuitikz}
  \draw (4.5, 0.5) to[closing switch, l=$S1$, a={VT=2.5 RON=1 ROFF=1e6}] (4.5, -0.5);
  \draw[dashed] (1.5, 0.5) to[short] (1.5, -0.5); % ctrl: S1
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        comp = model.components["S1"]
        assert comp.component_type == "VC Switch"
        terms = comp.get_terminal_positions()
        assert len(terms) == 4


class TestWaveformSourceRoundTrip:
    """Issue #524: Waveform Source parameters lost in CircuiTikZ round-trip."""

    def test_sin_waveform_params_restored(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[sV, l=$VW1$, a={SIN(0 5 1k 0 0 0)}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        comp = model.components["VW1"]
        assert comp.component_type == "Waveform Source"
        assert comp.waveform_type == "SIN"
        assert comp.waveform_params["SIN"]["offset"] == "0"
        assert comp.waveform_params["SIN"]["amplitude"] == "5"
        assert comp.waveform_params["SIN"]["frequency"] == "1k"

    def test_pulse_waveform_params_restored(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[sV, l=$VW1$, a={PULSE(0 5 0 1n 1n 500u 1m)}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        comp = model.components["VW1"]
        assert comp.waveform_type == "PULSE"
        assert comp.waveform_params["PULSE"]["v1"] == "0"
        assert comp.waveform_params["PULSE"]["v2"] == "5"
        assert comp.waveform_params["PULSE"]["per"] == "1m"

    def test_exp_waveform_params_restored(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[sV, l=$VW1$, a={EXP(0 5 0 1u 2u 2u)}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        comp = model.components["VW1"]
        assert comp.waveform_type == "EXP"
        assert comp.waveform_params["EXP"]["v1"] == "0"
        assert comp.waveform_params["EXP"]["tau2"] == "2u"

    def test_waveform_default_when_no_value(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[sV, l=$VW1$] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        comp = model.components["VW1"]
        assert comp.component_type == "Waveform Source"
        # Default waveform params should be initialized by ComponentData.__post_init__
        assert comp.waveform_type == "SIN"
        assert comp.waveform_params is not None

    def test_full_round_trip_preserves_waveform(self):
        """Export a waveform source and reimport — params must survive."""
        from models.circuit import CircuitModel
        from models.component import ComponentData
        from simulation.circuitikz_exporter import generate

        ws = ComponentData("VW1", "Waveform Source", "SIN(0 10 2k)", position=(100, 100))
        ws.waveform_type = "SIN"
        ws.waveform_params["SIN"]["offset"] = "0"
        ws.waveform_params["SIN"]["amplitude"] = "10"
        ws.waveform_params["SIN"]["frequency"] = "2k"

        model = CircuitModel()
        model.add_component(ws)
        model.rebuild_nodes()

        tex = generate(model.components, model.wires, model.nodes, model.terminal_to_node)
        reimported, warnings = import_circuitikz(tex)

        assert len(warnings) == 0
        comp = reimported.components["VW1"]
        assert comp.waveform_type == "SIN"
        assert comp.waveform_params["SIN"]["amplitude"] == "10"
        assert comp.waveform_params["SIN"]["frequency"] == "2k"


class TestWarnings:
    def test_unsupported_component_warning(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
  \draw (1, 1) to[unknown_thing, l=$X1$] (1, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert len(warnings) > 0
        assert any("unknown_thing" in w for w in warnings)

    def test_empty_input_raises_error(self):
        with pytest.raises(CircuitikzParseError):
            import_circuitikz("\\begin{circuitikz}\n\\end{circuitikz}")


class TestNoQtDependencies:
    def test_no_pyqt_imports(self):
        import simulation.circuitikz_parser as mod

        source = open(mod.__file__).read()
        assert "PyQt" not in source
        assert "QtCore" not in source
        assert "QtWidgets" not in source
