"""Tests for CircuiTikZ LaTeX parser."""

import pytest
from simulation.circuitikz_parser import CircuitikzParseError, import_circuitikz


class TestBasicParsing:
    def test_parse_single_resistor(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert len(model.components) == 1
        assert "R1" in model.components
        assert model.components["R1"].component_type == "Resistor"
        assert model.components["R1"].value == "1k"

    def test_parse_multiple_components(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 2) to[R, l=$R1$, a={1k}] (0, 1);
  \draw (0, 1) to[C, l=$C1$, a={10u}] (0, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert len(model.components) == 2
        assert "R1" in model.components
        assert "C1" in model.components
        assert model.components["C1"].component_type == "Capacitor"
        assert model.components["C1"].value == "10u"

    def test_parse_voltage_source(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[V, l=$V1$, a={5V}] (0, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert "V1" in model.components
        assert model.components["V1"].component_type == "Voltage Source"
        assert model.components["V1"].value == "5V"


class TestComponentTypes:
    def test_parse_inductor(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[L, l=$L1$, a={10m}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["L1"].component_type == "Inductor"

    def test_parse_diode(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[D, l=$D1$] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["D1"].component_type == "Diode"

    def test_parse_current_source(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[I, l=$I1$, a={1m}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["I1"].component_type == "Current Source"


class TestGroundParsing:
    def test_parse_ground(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
  \node[ground] at (0, 0) {};
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert any(c.component_type == "Ground" for c in model.components.values())


class TestTripoles:
    def test_parse_npn(self):
        tex = r"""
\begin{circuitikz}
  \node[npn] (Q1) at (2, 2) {};
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert "Q1" in model.components
        assert model.components["Q1"].component_type == "BJT NPN"

    def test_parse_opamp(self):
        tex = r"""
\begin{circuitikz}
  \node[op amp] (U1) at (3, 2) {};
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert "U1" in model.components
        assert model.components["U1"].component_type == "Op-Amp"


class TestWireParsing:
    def test_parse_wire(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 2) to[R, l=$R1$, a={1k}] (0, 1);
  \draw (0, 2) to[C, l=$C1$, a={10u}] (2, 2);
  \draw (0, 1) -- (2, 1);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        # Wire should be parsed (may or may not match terminals depending on positions)
        assert len(model.components) == 2


class TestStandaloneDocument:
    def test_parse_standalone(self):
        tex = r"""
% Generated by Spice-GUI
\documentclass[border=10pt]{standalone}
\usepackage[siunitx]{circuitikz}
\begin{document}
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
\end{circuitikz}
\end{document}
"""
        model, _ = import_circuitikz(tex)
        assert len(model.components) == 1
        assert "R1" in model.components


class TestValueExtraction:
    def test_extracts_value_from_annotation(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={4.7k\Omega}] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert "4.7k" in model.components["R1"].value

    def test_default_value_when_missing(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$] (0, 0);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        # Should get a default value for Resistor
        assert model.components["R1"].value != ""


class TestControlledSourceDisambiguation:
    """Issue #520: CircuiTikZ round-trip conflates CCVS with VCVS and CCCS with VCCS."""

    def test_ccvs_preserved_via_spice_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled voltage source, l=$H1$, a={1k}] (1.5, -0.5); % spice: CCVS
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["H1"].component_type == "CCVS"

    def test_cccs_preserved_via_spice_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled current source, l=$F1$, a={1}] (1.5, -0.5); % spice: CCCS
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["F1"].component_type == "CCCS"

    def test_vcvs_default_without_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled voltage source, l=$E1$, a={10}] (1.5, -0.5);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["E1"].component_type == "VCVS"

    def test_vccs_default_without_comment(self):
        tex = r"""
\begin{circuitikz}
  \draw (1.5, 0.5) to[american controlled current source, l=$G1$, a={1m}] (1.5, -0.5);
\end{circuitikz}
"""
        model, _ = import_circuitikz(tex)
        assert model.components["G1"].component_type == "VCCS"

    def test_full_round_trip_ccvs(self):
        """Export a CCVS and reimport — must come back as CCVS, not VCVS."""
        from models.circuit import CircuitModel
        from models.component import ComponentData
        from simulation.circuitikz_exporter import generate

        ccvs = ComponentData("H1", "CCVS", "1k", position=(100, 100))
        model = CircuitModel()
        model.add_component(ccvs)
        model.rebuild_nodes()

        tex = generate(model.components, model.wires, model.nodes, model.terminal_to_node)
        reimported, warnings = import_circuitikz(tex)

        assert len(warnings) == 0
        assert reimported.components["H1"].component_type == "CCVS"

    def test_full_round_trip_cccs(self):
        """Export a CCCS and reimport — must come back as CCCS, not VCCS."""
        from models.circuit import CircuitModel
        from models.component import ComponentData
        from simulation.circuitikz_exporter import generate

        cccs = ComponentData("F1", "CCCS", "1", position=(100, 100))
        model = CircuitModel()
        model.add_component(cccs)
        model.rebuild_nodes()

        tex = generate(model.components, model.wires, model.nodes, model.terminal_to_node)
        reimported, warnings = import_circuitikz(tex)

        assert len(warnings) == 0
        assert reimported.components["F1"].component_type == "CCCS"


class TestWarnings:
    def test_unsupported_component_warning(self):
        tex = r"""
\begin{circuitikz}
  \draw (0, 1) to[R, l=$R1$, a={1k}] (0, 0);
  \draw (1, 1) to[unknown_thing, l=$X1$] (1, 0);
\end{circuitikz}
"""
        model, warnings = import_circuitikz(tex)
        assert len(warnings) > 0
        assert any("unknown_thing" in w for w in warnings)

    def test_empty_input_raises_error(self):
        with pytest.raises(CircuitikzParseError):
            import_circuitikz("\\begin{circuitikz}\n\\end{circuitikz}")


class TestNoQtDependencies:
    def test_no_pyqt_imports(self):
        import simulation.circuitikz_parser as mod

        source = open(mod.__file__).read()
        assert "PyQt" not in source
        assert "QtCore" not in source
        assert "QtWidgets" not in source
